- name: Guardar cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Verificamos si el archivo existe antes de intentar agregarlo
          if [ -f sadi_historico.csv ]; then
            git add sadi_historico.csv
            # Solo hace commit si hay algo nuevo para subir
            git diff --quiet && git diff --staged --quiet || (git commit -m "Update datos $(date +'%Y-%m-%d %H:%M')" && git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main)
          else
            echo "El archivo sadi_historico.csv no fue creado. Saltando commit."
          fi
